
production:
  adapter: mysql
  database: baseball_tracker_prod
  username: timothyf
  password: 3121018
  host: mysql.timothyfisher.com
  
development:
  adapter: mysql
  database: baseball_tracker_dev
  username: root
  password:  
  host: localhost

test:
  adapter: mysql
  database: baseball_tracker_test
  username: root
  password:  
  host: localhost



