production:
  adapter: mysql
  database: baseball_tracker_prod
  username: root
  password: 
  host: localhost
  
development:
  adapter: mysql
  database: baseball_tracker_dev
  username: root
  password:  
  host: localhost

test:
  adapter: mysql
  database: baseball_tracker_test
  username: root
  password:  
  host: localhost



